/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
/**
 * Humboldt REST — JAX-RS filters for automatic HTTP endpoint instrumentation
 * on the server side (OpenTelemetry tracing).
 *
 * <p>M6b MVP: {@link io.vidocq.humboldt.rest.HumboldtServerRequestFilter} and
 * {@link io.vidocq.humboldt.rest.HumboldtServerResponseFilter} coupled via
 * {@code ContainerRequestContext.setProperty()}. Follows OTel HTTP
 * semantic conventions 1.27+.</p>
 */
module io.vidocq.humboldt.rest {

    requires transitive io.vidocq.humboldt.api;
    requires transitive io.vidocq.humboldt.sdk.trace;
    requires transitive io.vidocq.humboldt.propagator.w3c;
    requires transitive io.opentelemetry.api;
    requires transitive io.opentelemetry.context;
    requires transitive jakarta.ws.rs;
    requires jakarta.annotation;  // @Priority on HumboldtSpanFinalizer + Client*Filter
    requires static jakarta.cdi;  // @Dependent on the server filters (runtime brings CDI)
    requires static io.vidocq.vauban.api;  // generated _VaubanComponents provider (runtime brings Vauban)
    requires java.logging;
    // MicroProfile Rest Client: optional. HumboldtMpRestClientListener only runs when a Rest
    // Client is present at run time (cyrano-core brings it); read through the module Vidocq
    // ships, cyrano's repackaged API (humboldt#18). `requires static` = compile time only.
    requires static io.vidocq.cyrano.mp.rest.client.api;

    exports io.vidocq.humboldt.rest;

    // M7c.7 — Auto-discovery by CassiniClientBuilder (and any compatible JAX-RS Client)
    // which scans ServiceLoader<Feature> at build() — automatically instruments outbound
    // requests with a kind=CLIENT span (conformant with MP Telemetry §3.2).
    provides jakarta.ws.rs.core.Feature
            with io.vidocq.humboldt.rest.HumboldtClientTracingFeature;

    // M7c.12 — Auto-instrumentation of MP Rest Clients via the standard SPI
    // RestClientListener.onNewClient() (MP Rest Client 4.0 spec §10.2). Implemented
    // by Cyrano in CyranoRestClientBuilder.build().
    provides org.eclipse.microprofile.rest.client.spi.RestClientListener
            with io.vidocq.humboldt.rest.HumboldtMpRestClientListener;

    // In-module component provider generated by the Vauban APT (create/injectField).
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.humboldt.rest._VaubanComponents;
}
